language: node_js

sudo: false

node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test

notifications:
  emails:
    recipients:  
    - ashzhouyue@gmail.com  
    on_success: always  
    on_failure: always  